apiVersion: v2
name: dragalia-api
description: A Helm chart for the Dragalia Lost server emulator

type: application

version: 2.1.0
appVersion: "latest"

dependencies:
  - name: postgresql
    version: ~13.2.0
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: ~18.2.0
    repository: https://charts.bitnami.com/bitnami
