# Default values for dragalia-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sapiensanatis/dragalia-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

aspnet:
  # ASPNETCORE_ENVIRONMENT env variable.
  # If Staging or Develop, the databse will be automatically migrated at startup.
  # For Production it won't be and a manual migration is required.
  environment: Staging
  logs:
    # The folder to save logs to
    folder: /dragalia-api/logs
    # The size of the log volume
    maxSize: 5Gi
    # How many log files to retain
    retainedFileCount: 31
    # When to roll over log files
    rollingInterval: Day
    # Minimum log level
    level: Information # TODO: Configurable EFCore/ASP.NET logging overrides (currently always 'Warning')
  secret:
    # Pepper string to use for hashed passwords
    # Not used if BaaS login is enabled
    hashSalt: dragalia
    # Token to require when performing savefile import/delete
    developerToken: token
  redis:
    # Login session key expiry time in minutes
    sessionExpiryTime: 60
    # Dungeon (i.e. quest) session key expiry time in minutes
    dungeonExpiryTime: 60
  auth:
    # Use the new login flow relying on an external service
    useBaasLogin: true
    # Expected issuer of login JWTs
    tokenIssuer: LukeFZ
    # Expected audience of login JWTs
    tokenAudience: baas-Id
    # URL of login server (to fetch jwks.json)
    baasUrl: https://baas.lukefz.xyz
  dragalipatch:
    # Mode to send to Dragalipatch
    mode: "RAW"


# Ingress settings. Customize as appropriate to your domain and TLS setup
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
    
redis:
  auth:
    enabled: false
  volumePermissions:
    enabled: true

postgresql:
  auth:
    # Postgres password. Should be changed from the default.
    postgresPassword: midgardsormr2
  volumePermissions:
    enabled: true

service:
  type: ClusterIP
  port: 80

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
