apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dragalia-api.fullname" . }}
data:
  appsettings.json: |+
    {
        "Serilog": {
            "MinimumLevel": {
                "Default": "Information",
                "Override": {
                    "Microsoft.AspNetCore": "Warning",
                    "Microsoft.EntityFrameworkCore": "Warning"
                }
            },
            "WriteTo": [
                {
                    "Name": "Console",
                    "Args": {
                        "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3} {SourceContext}][{RequestId}][{DeviceAccountId}] {Message:l}{NewLine}{Exception}"
                    }
                },
                {
                    "Name": "File",
                    "Args": {
                        "outputTemplate": "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3} {SourceContext}][{RequestId}][{DeviceAccountId}] {Message:l}{NewLine}{Exception}",
                        "path": "logs/dragalia-api_.log",
                        "rollingInterval": "{{ .Values.aspnet.logs.rollingInterval }}",
                        "rollOnFileSizeLimit": true,
                        "fileSizeLimitBytes": 1000000000,
                        "retainedFileCountLimit": {{ .Values.aspnet.logs.retainedFileCount }}
                    }
                }
            ]
        },
        "AllowedHosts": "*",
        "ConnectionStrings": {
            "RedisHost": "{{ include "dragalia-api.fullname" . }}-redis-master",
            "PostgresHost": "{{ include "dragalia-api.fullname" . }}-postgresql"
        },
        "HashSalt": "{{ .Values.aspnet.secret.hashSalt }}",
        "SessionExpiryTimeMinutes": {{ .Values.aspnet.redis.sessionExpiryTime }},
        "DungeonExpiryTimeMinutes": {{ .Values.aspnet.redis.dungeonExpiryTime }},
    }
  