apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dragalia-api.fullname" . }}
data:
  appsettings.json: |+
    {
        "Serilog": {
            "MinimumLevel": {
                "Default": "{{ .Values.aspnet.logs.minimumLevel }}",
            },
            "WriteTo": [
                {
                    "Name": "Console"
                },
                {
                    "Name": "File",
                    "Args": {
                        "path": "logs/dragalia-api_.log",
                        "rollingInterval": "{{ .Values.aspnet.logs.rollingInterval }}",
                        "rollOnFileSizeLimit": true,
                        "fileSizeLimitBytes": 1000000000,
                        "retainedFileCountLimit": {{ .Values.aspnet.logs.retainedFileCount }}
                    }
                }
                {{- if .Values.seq.enabled }},
                {
                    "Name": "Seq",
                    "Args": {
                        "serverUrl": "{{ .Values.seq.hostname }}",
                        "apiKey": "{{ .Values.seq.apiKey }}",
                        "restrictedToMinimumLevel": "Verbose"
                    }
                }
                {{- end }}
            ]
        },
        "AllowedHosts": "*",
        "ConnectionStrings": {
            "RedisHost": "{{ include "dragalia-api.fullname" . }}-redis-master",
            "PostgresHost": "{{ include "dragalia-api.fullname" . }}-postgresql"
        },
        "Login": {
            "UseBaasLogin": {{ .Values.aspnet.auth.useBaasLogin }}
        },
        "Baas": {
            "TokenIssuer": "{{ .Values.aspnet.auth.tokenIssuer }}",
            "TokenAudience": "{{ .Values.aspnet.auth.tokenAudience }}",
            "BaasUrl": "{{ .Values.aspnet.auth.baasUrl }}"
        },
        "Dragalipatch": {
            "Mode": "{{ .Values.aspnet.dragalipatch.mode }}"
        },
        "HashSalt": "{{ .Values.aspnet.secret.hashSalt }}",
        "Redis": {
            "SessionExpiryTimeMinutes": {{ .Values.aspnet.redis.sessionExpiryTime }},
            "DungeonExpiryTimeMinutes": {{ .Values.aspnet.redis.dungeonExpiryTime }},
        }
    }
