apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dragalia-api.fullname" . }}
data:
  appsettings.json: |+
    {
        "Serilog": {
            "MinimumLevel": {
                "Default": "{{ .Values.aspnet.logs.minimumLevel }}",
                "Override": {{- .Values.aspnet.logs.overrideMinimumLevel | mustToPrettyJson | indent 16 }}
            },
            "WriteTo": [
                {
                    "Name": "Console"
                },
                {
                    "Name": "Async",
                    "Args": {
                        "configure": [
                            {
                                "Name": "File",
                                "Args": {
                                    "path": "logs/dragalia-api_.log",
                                    "rollingInterval": "{{ .Values.aspnet.logs.rollingInterval }}",
                                    "rollOnFileSizeLimit": true,
                                    "fileSizeLimitBytes": 1000000000,
                                    "retainedFileCountLimit": {{ .Values.aspnet.logs.retainedFileCount }}
                                }
                            }
                        ]
                    }
                }
                {{- if .Values.seq.enabled }},
                {
                    "Name": "Seq",
                    "Args": {
                        "serverUrl": "{{ .Values.seq.hostname }}",
                        "apiKey": "{{ .Values.seq.apiKey }}",
                        "restrictedToMinimumLevel": "Verbose"
                    }
                }
                {{- end }}
            ]
        },
        "AllowedHosts": "*",
        "ConnectionStrings": {
            "RedisHost": "{{ .Release.Name }}-redis-master",
            "PostgresHost": "{{ .Release.Name }}-postgresql"
        },
        "Login": {
            "UseBaasLogin": {{ .Values.aspnet.auth.useBaasLogin }}
        },
        "Baas": {
            "TokenIssuer": "{{ .Values.aspnet.auth.tokenIssuer }}",
            "TokenAudience": "{{ .Values.aspnet.auth.tokenAudience }}",
            "BaasUrl": "{{ .Values.aspnet.auth.baasUrl }}",
            "ClientId": "{{ .Values.aspnet.auth.clientId }}",
            "ChallengeString": "{{ .Values.aspnet.auth.challengeString }}"
        },
        "Dragalipatch": {
            "Mode": "{{ .Values.aspnet.dragalipatch.mode }}",
            "CdnUrl": "{{ .Values.aspnet.dragalipatch.cdnUrl }}"
        },
        "HashSalt": "{{ .Values.aspnet.secret.hashSalt }}",
        "Redis": {
            "SessionExpiryTimeMinutes": {{ .Values.aspnet.redis.sessionExpiryTime }},
            "DungeonExpiryTimeMinutes": {{ .Values.aspnet.redis.dungeonExpiryTime }}
        },
        "PhotonOptions": {
            "ServerUrl": "{{ .Values.aspnet.photon.serverUrl }}",
            "StateManagerUrl": "{{ .Values.aspnet.photon.stateManagerUrl }}"
        },
         "ResourceVersionOptions": {
            "Android": "{{ .Values.aspnet.resourceVersion.android }}",
            "Ios": "{{ .Values.aspnet.resourceVersion.ios }}"
        },
        "BlazorOptions": {
            "BaseImagePath": "{{ .Values.aspnet.blazor.baseImagePath }}"
        },
        "EventOptions": {
            "EventList": [
              {{- range .Values.aspnet.events }}
                {
                  "Id": {{ .id }},
                  "Start": {{ .start | quote }},
                  "End": {{ .end | quote }}
                }
              {{- end}}
            ]
        }
    }
