{{- if .Values.postgresqlBackup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
spec:
  schedule: {{ .Values.postgresqlBackup.cron | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: postgres
              image: postgres:16
              imagePullPolicy: IfNotPresent
              command: 
                - sh
                - -c
                - >
                  echo Connecting to host dragalia-api-postgresql;
                  pg_dump {{ .Values.postgresql.auth.database }}
                  --username=postgres 
                  --no-password
                  --format=custom
                  --file=/backups/dragalia-api-$(date +"%Y-%m-%d_%H-%M-%S").bak
                  --host=dragalia-api-postgresql
                  --verbose
              volumeMounts:
                - name: data
                  mountPath: /backups
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dragalia-api-postgresql
                      key: postgres-password
                      optional: false
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "dragalia-api.fullname" . }}-db-backup
{{- end }}