{{- if .Values.postgresqlBackup.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dragalia-api.fullname" . }}-db-backup
spec:
  volumeName: {{ include "dragalia-api.fullname" . }}-db-backup
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresqlBackup.maxSize }}
{{- end }}