{{- if .Values.postgresqlBackup.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dragalia-api.fullname" . }}-db-backup
  labels:
    type: local
spec:
  storageClassName: "manual"
  claimRef:
    namespace: default
    name: {{ include "dragalia-api.fullname" . }}-db-backup
  capacity:
    storage: {{ .Values.postgresqlBackup.maxSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.postgresqlBackup.path | quote }}
{{- end }}