apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "dragalia-api.fullname" . }}
  labels:
    type: local
spec:
  claimRef:
    namespace: default
    name: {{ include "dragalia-api.fullname" . }}
  storageClassName: "manual"
  capacity:
    storage: {{ .Values.aspnet.logs.maxSize }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.aspnet.logs.path | quote }}