apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dragalia-api.fullname" . }}
data:
  developerToken: {{ .Values.aspnet.secret.developerToken | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  postgres-password: {{ .Values.postgresPassword | b64enc }}
