apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dragalia-api.fullname" . }}-aspnet
data:
  developerToken: {{ .Values.aspnet.secret.developerToken | b64enc }}
  photonToken: {{ .Values.aspnet.photon.token | b64enc }}
  zenaToken: {{ .Values.aspnet.photon.zenaToken | b64enc }}
